# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Banana Time
tagline:             'thoughts and code sketches'
description:         'Musings, experiments, and observations.'
url:                 http://michaelplaing@github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Michael Laing
  url:               ''
  email:             mlaing@post.harvard.edu

# Custom vars
version:             1.0.0
